"use strict";
const KEY="nexus-finance-v3",OLD_KEYS=["nxs_trans","nxs_budgets","nxs_goals","nxs_accounts","nxs_check"];
const $=id=>document.getElementById(id),money=n=>hidden?"R$ •••••":Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const today=()=>new Date().toISOString().slice(0,10),periodOf=d=>String(d).slice(0,7);
let hidden=false,cashChart,expenseChart;

function read(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));return value??fallback}catch{return fallback}}
function initialState(){return{version:3,accounts:[{id:"acc-main",name:"Conta principal",openingBalance:0}],transactions:[],bills:[],budgets:[],goals:[]}}
function migrate(){const saved=read(KEY,null);if(saved)return normalize(saved);const oldAccounts=read("nxs_accounts",[]),accounts=(oldAccounts.length?oldAccounts:["Conta principal"]).map((a,i)=>({id:`acc-${i}`,name:String(a),openingBalance:0}));const accountId=name=>accounts.find(a=>a.name===name)?.id||accounts[0].id;return normalize({version:3,accounts,transactions:read("nxs_trans",[]).map(t=>({id:String(t.id||uid("tx")),description:t.desc||t.description||"Lançamento",amount:Number(t.amount)||0,date:t.date||today(),type:t.type==="transfer"?"goal":t.type,category:t.category||"Outros",accountId:accountId(t.account),notes:t.justification||t.notes||""})),bills:read("nxs_check",[]).map(b=>({...b,id:String(b.id),accountId:accounts[0].id})),budgets:read("nxs_budgets",[]),goals:read("nxs_goals",[])})}
function normalize(s){const base=initialState();s={...base,...s};s.accounts=(s.accounts||[]).map((a,i)=>typeof a==="string"?{id:`acc-${i}`,name:a,openingBalance:0}:{id:String(a.id||uid("acc")),name:String(a.name||"Conta"),openingBalance:Number(a.openingBalance)||0});if(!s.accounts.length)s.accounts=base.accounts;s.transactions=(s.transactions||[]).filter(t=>t&&t.date).map(t=>({...t,id:String(t.id||uid("tx")),description:String(t.description||t.desc||"Lançamento"),amount:Math.abs(Number(t.amount)||0),type:["income","expense","goal"].includes(t.type)?t.type:"expense",accountId:t.accountId||s.accounts.find(a=>a.name===t.account)?.id||s.accounts[0].id,category:String(t.category||"Outros"),notes:String(t.notes||t.justification||"")}));s.bills=s.bills||[];s.budgets=s.budgets||[];s.goals=s.goals||[];return s}
let state=migrate();save();
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(msg){const el=$("toast");el.textContent=msg;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2600)}
function accountName(id){return state.accounts.find(a=>a.id===id)?.name||"Conta removida"}
function balance(account){return account.openingBalance+state.transactions.filter(t=>t.accountId===account.id).reduce((n,t)=>n+(t.type==="income"?t.amount:-t.amount),0)}
function selected(){const mode=$("view-mode").value,y=$("filter-year").value,m=$("filter-month").value;return state.transactions.filter(t=>mode==="all"||t.date.startsWith(mode==="year"?y:`${y}-${m}`))}
function selectedPeriod(){return `${$("filter-year").value}-${$("filter-month").value}`}
function setOptions(){const options=state.accounts.map(a=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join("");["tx-account","bill-account","payment-account"].forEach(id=>$(id).innerHTML=options);const categories=[...new Set([...state.budgets.map(b=>b.name),...state.transactions.map(t=>t.category),"Moradia","Alimentação","Transporte","Saúde","Lazer","Outros"])];const goals=state.goals.map(g=>`<option value="${esc(g.name)}">${esc(g.name)}</option>`).join("");$("tx-category").innerHTML=categories.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join("")+goals}
function initFilters(){const now=new Date(),years=new Set([now.getFullYear(),...state.transactions.map(t=>Number(t.date.slice(0,4)))]);$("filter-year").innerHTML=[...years].sort((a,b)=>b-a).map(y=>`<option>${y}</option>`).join("");$("filter-month").innerHTML=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"].map((n,i)=>`<option value="${String(i+1).padStart(2,"0")}">${n}</option>`).join("");$("filter-month").value=String(now.getMonth()+1).padStart(2,"0")}
function render(){setOptions();const txs=selected(),income=txs.filter(t=>t.type==="income").reduce((n,t)=>n+t.amount,0),expense=txs.filter(t=>t.type==="expense").reduce((n,t)=>n+t.amount,0),total=state.accounts.reduce((n,a)=>n+balance(a),0),period=selectedPeriod(),pending=state.bills.filter(b=>!b.payments?.[period]).reduce((n,b)=>n+Number(b.amount||0),0);$("main-balance").textContent=money(total);$("kpi-income").textContent=money(income);$("kpi-expense").textContent=money(expense);$("kpi-result").textContent=money(income-expense);$("kpi-result").className=income-expense>=0?"positive":"negative";$("kpi-pending").textContent=money(pending);$("period-label").textContent=$("view-mode").value==="all"?"Patrimônio disponível em todas as contas":`Indicadores do período selecionado`;$("accounts-rail").innerHTML=state.accounts.map(a=>`<article class="account-card"><span>${esc(a.name)}</span><strong>${money(balance(a))}</strong></article>`).join("");renderAlerts(period);renderBills(period);renderBudgets(txs);renderGoals();renderHistory();renderRecent(txs);renderAccounts();renderCharts(txs)}
function renderAlerts(period){const overdue=state.bills.filter(b=>!b.payments?.[period]&&Number(b.day)<new Date().getDate()&&period===today().slice(0,7));$("alerts").innerHTML=overdue.length?`<div class="alert"><strong>${overdue.length} conta(s) vencida(s).</strong> Confira o checklist mensal.</div>`:""}
function renderBills(period){$("bills-grid").innerHTML=state.bills.length?state.bills.map(b=>{const paid=b.payments?.[period];return `<article class="item-card"><div class="item-top"><div><strong>${esc(b.name)}</strong><small>Vence dia ${Number(b.day)}</small></div><strong>${money(b.amount)}</strong></div><p class="muted small">${esc(b.category||"Outros")} · ${esc(accountName(b.accountId))}</p><div class="item-actions">${paid?`<span class="positive small">Pago em ${esc(paid.date?.split("-").reverse().join("/")||"")}</span>`:`<button class="mini-button" data-pay="${esc(b.id)}">Registrar pagamento</button>`}<button class="mini-button" data-delete-bill="${esc(b.id)}">Excluir</button></div></article>`}).join(""):`<p class="empty">Nenhuma conta fixa cadastrada.</p>`}
function renderBudgets(txs){$("budgets-grid").innerHTML=state.budgets.length?state.budgets.map(b=>{const spent=txs.filter(t=>t.type==="expense"&&t.category===b.name).reduce((n,t)=>n+t.amount,0),limit=Number(b.limit)||0,p=Math.min(100,limit?spent/limit*100:0);return `<article class="item-card"><div class="item-top"><strong>${esc(b.name)}</strong><strong class="${spent>limit?"negative":""}">${money(spent)}</strong></div><div class="progress"><span style="width:${p}%"></span></div><p class="muted small">${p.toFixed(0)}% de ${money(limit)}</p><div class="item-actions"><button class="mini-button" data-delete-budget="${esc(b.id)}">Excluir</button></div></article>`}).join(""):`<p class="empty">Crie limites para acompanhar seus gastos.</p>`}
function renderGoals(){const saved=name=>state.transactions.filter(t=>t.type==="goal"&&t.category===name).reduce((n,t)=>n+t.amount,0);$("goals-grid").innerHTML=state.goals.length?state.goals.map(g=>{const value=saved(g.name),p=Math.min(100,value/Number(g.target)*100||0);return `<article class="item-card"><div class="item-top"><strong>${esc(g.name)}</strong><strong>${money(value)}</strong></div><div class="progress"><span style="width:${p}%;background:var(--blue)"></span></div><p class="muted small">${p.toFixed(0)}% de ${money(g.target)}</p><div class="item-actions"><button class="mini-button" data-delete-goal="${esc(g.id)}">Excluir</button></div></article>`}).join(""):`<p class="empty">Nenhuma meta criada.</p>`}
function filteredHistory(){const q=$("history-search").value.toLowerCase(),type=$("history-type").value;return selected().filter(t=>(type==="all"||t.type===type)&&[t.description,t.category,accountName(t.accountId)].some(v=>String(v).toLowerCase().includes(q)))}
function txRow(t){const sign=t.type==="income"?1:-1,label={income:"Entrada",expense:"Saída",goal:"Meta"}[t.type];return `<tr><td>${t.date.split("-").reverse().join("/")}</td><td><strong>${esc(t.description)}</strong>${t.notes?`<br><small class="muted">${esc(t.notes)}</small>`:""}</td><td>${esc(t.category)}</td><td>${esc(accountName(t.accountId))}</td><td>${label}</td><td class="${sign>0?"positive":"negative"}">${sign>0?"+":"−"} ${money(t.amount)}</td><td><button class="mini-button" data-delete-tx="${esc(t.id)}">Excluir</button></td></tr>`}
function renderHistory(){$("history-body").innerHTML=filteredHistory().sort((a,b)=>b.date.localeCompare(a.date)).map(txRow).join("")||`<tr><td colspan="7" class="empty">Nenhum lançamento encontrado.</td></tr>`}
function renderRecent(txs){$("recent-list").innerHTML=txs.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(t=>`<div class="activity"><span class="activity-icon">${t.type==="income"?"↑":t.type==="goal"?"◎":"↓"}</span><div class="activity-main"><strong>${esc(t.description)}</strong><small>${esc(t.category)} · ${t.date.split("-").reverse().join("/")}</small></div><span class="activity-value ${t.type==="income"?"positive":"negative"}">${money(t.amount)}</span></div>`).join("")||`<p class="empty">Registre sua primeira movimentação.</p>`}
function renderAccounts(){$("account-list").innerHTML=state.accounts.map(a=>`<div class="setting-row"><div><strong>${esc(a.name)}</strong><small>Saldo inicial: ${money(a.openingBalance)}</small></div><button class="mini-button" data-delete-account="${esc(a.id)}">Excluir</button></div>`).join("")}
function renderCharts(txs){if(typeof Chart==="undefined")return;cashChart?.destroy();expenseChart?.destroy();const monthly=$("view-mode").value==="month",labels=monthly?Array.from({length:new Date(Number($("filter-year").value),Number($("filter-month").value),0).getDate()},(_,i)=>i+1):["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"],inc=labels.map(()=>0),out=labels.map(()=>0);txs.forEach(t=>{const i=monthly?Number(t.date.slice(8,10))-1:Number(t.date.slice(5,7))-1;if(t.type==="income")inc[i]+=t.amount;else out[i]+=t.amount});Chart.defaults.color="#888";cashChart=new Chart($("cash-chart"),{type:"bar",data:{labels,datasets:[{label:"Entradas",data:inc,backgroundColor:"#43d17a",borderRadius:4},{label:"Saídas e metas",data:out,backgroundColor:"#e50914",borderRadius:4}]},options:{responsive:true,maintainAspectRatio:false,scales:{x:{grid:{display:false}},y:{grid:{color:"#292929"}}}}});const map={};txs.filter(t=>t.type==="expense").forEach(t=>map[t.category]=(map[t.category]||0)+t.amount);expenseChart=new Chart($("expense-chart"),{type:"doughnut",data:{labels:Object.keys(map).length?Object.keys(map):["Sem despesas"],datasets:[{data:Object.keys(map).length?Object.values(map):[1],backgroundColor:["#e50914","#f5b942","#4d8dff","#43d17a","#8e44ad","#777"],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:"68%",plugins:{legend:{position:"bottom"}}}})}
function remove(kind,id){const map={tx:"transactions",bill:"bills",budget:"budgets",goal:"goals",account:"accounts"},list=map[kind];if(kind==="account"&&(state.accounts.length===1||state.transactions.some(t=>t.accountId===id)||state.bills.some(b=>b.accountId===id)))return toast("A conta possui vínculos ou é a única cadastrada.");if(confirm("Confirma a exclusão?")){state[list]=state[list].filter(x=>String(x.id)!==id);save();render();toast("Item excluído.")}}
function download(name,text,type){const a=document.createElement("a"),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
const csvCell=v=>`"${String(v??"").replace(/"/g,'""')}"`,csvHeaders=["Data","Tipo","Descrição","Categoria","Conta","Valor","Observações"];
function csvText(rows){return "\ufeff"+[csvHeaders,...rows].map(r=>r.map(csvCell).join(";")).join("\r\n")}
function parseCSV(text){const delimiter=(text.split(/\r?\n/,1)[0].match(/;/g)||[]).length>=(text.split(/\r?\n/,1)[0].match(/,/g)||[]).length?";":",";const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===delimiter&&!quoted){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
function numberBR(v){let s=String(v).replace(/R\$|\s/g,"");if(s.includes(","))s=s.replace(/\./g,"").replace(",",".");return Math.abs(Number(s))}
function importCSV(text){const rows=parseCSV(text.replace(/^\ufeff/,""));if(rows.length<2)throw Error("O arquivo não possui lançamentos.");const norm=s=>String(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase(),heads=rows.shift().map(norm),idx=n=>heads.indexOf(norm(n));let count=0;rows.forEach(r=>{let date=r[idx("Data")],type=norm(r[idx("Tipo")]);if(/^\d{2}\/\d{2}\/\d{4}$/.test(date)){const[d,m,y]=date.split("/");date=`${y}-${m}-${d}`}type=type.startsWith("entr")||type==="income"?"income":type.startsWith("meta")||type==="goal"?"goal":"expense";const amount=numberBR(r[idx("Valor")]),description=r[idx("Descrição")],accName=r[idx("Conta")];if(!date||!amount||!description)return;let acc=state.accounts.find(a=>norm(a.name)===norm(accName));if(!acc){acc={id:uid("acc"),name:accName||"Conta importada",openingBalance:0};state.accounts.push(acc)}state.transactions.push({id:uid("tx"),date,type,description,category:r[idx("Categoria")]||"Outros",accountId:acc.id,amount,notes:r[idx("Observações")]||""});count++});if(!count)throw Error("Nenhuma linha válida foi encontrada.");save();return count}

document.addEventListener("DOMContentLoaded",()=>{initFilters();$("tx-date").value=today();$("payment-date").value=today();render();document.addEventListener("click",e=>{const b=e.target.closest("button,[data-action]");if(!b)return;if(b.dataset.section){document.querySelectorAll(".page,.nav-item").forEach(x=>x.classList.remove("active"));$(b.dataset.section).classList.add("active");document.querySelector(`.nav-item[data-section="${b.dataset.section}"]`)?.classList.add("active");document.querySelector(".sidebar").classList.remove("open");document.querySelector(".sidebar-overlay").classList.remove("open")}if(b.dataset.action==="menu"){document.querySelector(".sidebar").classList.toggle("open");document.querySelector(".sidebar-overlay").classList.toggle("open")}if(b.dataset.open){setOptions();$(b.dataset.open).showModal()}for(const k of ["tx","bill","budget","goal","account"])if(b.dataset[`delete${k[0].toUpperCase()+k.slice(1)}`])remove(k,b.dataset[`delete${k[0].toUpperCase()+k.slice(1)}`]);if(b.dataset.pay){const bill=state.bills.find(x=>String(x.id)===b.dataset.pay);$("payment-bill-id").value=bill.id;$("payment-amount").value=bill.amount;$("payment-account").value=bill.accountId;$("payment-modal").showModal()}});["view-mode","filter-month","filter-year"].forEach(id=>$(id).addEventListener("change",()=>{$("filter-month").hidden=$("view-mode").value!=="month";$("filter-year").hidden=$("view-mode").value==="all";render()}));["history-search","history-type"].forEach(id=>$(id).addEventListener("input",renderHistory));$("privacy-button").onclick=()=>{hidden=!hidden;render()};
$("transaction-form").addEventListener("submit",e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();state.transactions.push({id:uid("tx"),description:$("tx-description").value.trim(),amount:Number($("tx-amount").value),date:$("tx-date").value,type:$("tx-type").value,category:$("tx-category").value,accountId:$("tx-account").value,notes:$("tx-notes").value.trim()});save();e.target.reset();$("tx-date").value=today();$("transaction-modal").close();render();toast("Lançamento salvo.")});
$("bill-form").addEventListener("submit",e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();state.bills.push({id:uid("bill"),name:$("bill-name").value.trim(),amount:Number($("bill-amount").value),day:Number($("bill-day").value),category:$("bill-category").value.trim(),accountId:$("bill-account").value,payments:{}});save();e.target.reset();$("bill-modal").close();render()});
$("payment-form").addEventListener("submit",e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const b=state.bills.find(x=>String(x.id)===$("payment-bill-id").value),date=$("payment-date").value,tx={id:uid("tx"),description:b.name,amount:Number($("payment-amount").value),date,type:"expense",category:b.category,accountId:$("payment-account").value,notes:"Pagamento de conta fixa"};b.payments=b.payments||{};b.payments[periodOf(date)]={date,transactionId:tx.id};state.transactions.push(tx);save();$("payment-modal").close();render();toast("Pagamento registrado.")});
$("budget-form").addEventListener("submit",e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();state.budgets.push({id:uid("budget"),name:$("budget-name").value.trim(),limit:Number($("budget-limit").value)});save();e.target.reset();$("budget-modal").close();render()});$("goal-form").addEventListener("submit",e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();state.goals.push({id:uid("goal"),name:$("goal-name").value.trim(),target:Number($("goal-target").value)});save();e.target.reset();$("goal-modal").close();render()});$("account-form").addEventListener("submit",e=>{e.preventDefault();state.accounts.push({id:uid("acc"),name:$("account-name").value.trim(),openingBalance:Number($("account-opening").value)});save();e.target.reset();$("account-opening").value=0;render()});
$("csv-template").onclick=()=>download("modelo-nexus-finance.csv",csvText([[today(),"Saída","Exemplo","Alimentação","Conta principal","25,90","Apague esta linha"]]),"text/csv;charset=utf-8");$("csv-export").onclick=()=>download(`nexus-lancamentos-${today()}.csv`,csvText(state.transactions.map(t=>[t.date,{income:"Entrada",expense:"Saída",goal:"Meta"}[t.type],t.description,t.category,accountName(t.accountId),t.amount.toFixed(2).replace(".",","),t.notes])),"text/csv;charset=utf-8");$("csv-import").onclick=()=>$("csv-file").click();$("csv-file").onchange=async e=>{try{const n=importCSV(await e.target.files[0].text());render();$("file-status").textContent=`${n} lançamento(s) importado(s).`;toast("Importação concluída.")}catch(err){$("file-status").textContent=err.message}e.target.value=""};$("backup-export").onclick=()=>download(`nexus-backup-${today()}.json`,JSON.stringify(state,null,2),"application/json");$("backup-import").onclick=()=>$("backup-file").click();$("backup-file").onchange=async e=>{try{const data=normalize(JSON.parse(await e.target.files[0].text()));if(!confirm("Substituir os dados atuais pelo backup selecionado?"))return;state=data;save();render();toast("Backup restaurado.")}catch{$("file-status").textContent="Backup inválido."}e.target.value=""};$("reset-app").onclick=()=>{if(confirm("Apagar todos os dados do Nexus Finance? Faça um backup antes.")){localStorage.removeItem(KEY);OLD_KEYS.forEach(k=>localStorage.removeItem(k));state=initialState();save();render();toast("Dados do aplicativo apagados.")}}});
